version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: real-time-task-manager-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
